version: '3.5'

services:
  static:
    image: "demos"
    container_name: "demos"
    working_dir: /demos
    build:
      context: "../"
      dockerfile: "docker/static/Dockerfile"
    ports:
      - "8080:80"
    volumes:
      - "../:/demos/"
      - "../docker/static/demos.conf:/etc/nginx/conf.d/default.conf"
volumes:
  tmp:
  root: